version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: MySqlConnector
    versions:
    - 1.3.2
    - 1.3.3
    - 1.3.4
    - 1.3.7
  - dependency-name: Swashbuckle.AspNetCore
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.1.3
  - dependency-name: FluentValidation
    versions:
    - 10.0.0
    - 10.0.1
    - 10.0.2
    - 10.0.3
    - 10.0.4
    - 9.5.3
    - 9.5.4
  - dependency-name: Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore
    versions:
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore
    versions:
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.EntityFrameworkCore
    versions:
    - 5.0.5
  - dependency-name: Microsoft.AspNetCore.Authentication.JwtBearer
    versions:
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.AspNetCore.Identity.EntityFrameworkCore
    versions:
    - 5.0.5
  - dependency-name: Microsoft.EntityFrameworkCore.Relational
    versions:
    - 5.0.5
  - dependency-name: Serilog.AspNetCore
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: Newtonsoft.Json
    versions:
    - 13.0.1
